name: Test Environment Variables

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    environment: development # Referenciando o ambiente que você criou

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8" # ou a versão que você está usando

      - name: Run environment test
        run: python test_env.py
        # env:
        #   MY_SECRET: ${{ secrets.MY_SECRET }} # Referencie seu segredo
